-- 小程序用户表
CREATE TABLE IF NOT EXISTS mini_program_user (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    openid VARCHAR(100) NOT NULL UNIQUE COMMENT '微信OpenID',
    union_id VARCHAR(100) COMMENT '微信UnionID',
    nickname VARCHAR(100) COMMENT '昵称',
    avatar_url VARCHAR(500) COMMENT '头像URL',
    gender INT COMMENT '性别 0-未知 1-男 2-女',
    country VARCHAR(50) COMMENT '国家',
    province VARCHAR(50) COMMENT '省份',
    city VARCHAR(50) COMMENT '城市',
    phone VARCHAR(20) COMMENT '手机号',
    session_key VARCHAR(100) COMMENT '会话密钥',
    today_divination_count INT NOT NULL DEFAULT 0 COMMENT '今日占卜次数',
    last_divination_date DATETIME COMMENT '最后占卜日期',
    total_divination_count INT NOT NULL DEFAULT 0 COMMENT '总占卜次数',
    enabled BOOLEAN NOT NULL DEFAULT TRUE COMMENT '是否启用',
    created_at DATETIME NOT NULL COMMENT '创建时间',
    updated_at DATETIME COMMENT '更新时间',
    last_login_at DATETIME COMMENT '最后登录时间',
    INDEX idx_openid (openid),
    INDEX idx_union_id (union_id),
    INDEX idx_created_at (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='小程序用户表';

-- 占卜记录表
CREATE TABLE IF NOT EXISTS divination_record (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键ID',
    user_id BIGINT COMMENT '用户ID',
    openid VARCHAR(100) NOT NULL COMMENT '用户OpenID',
    question TEXT NOT NULL COMMENT '问题/所求之事',
    divination_method VARCHAR(20) NOT NULL COMMENT '占卜方法',
    original_hexagram_id INT NOT NULL COMMENT '本卦ID',
    original_hexagram_name VARCHAR(50) COMMENT '本卦名称',
    original_hexagram_binary VARCHAR(10) COMMENT '本卦二进制',
    changed_hexagram_id INT COMMENT '变卦ID',
    changed_hexagram_name VARCHAR(50) COMMENT '变卦名称',
    changed_hexagram_binary VARCHAR(10) COMMENT '变卦二进制',
    changing_lines VARCHAR(50) COMMENT '动爻列表JSON',
    lines_detail TEXT COMMENT '六爻详细信息JSON',
    interpretation TEXT COMMENT '基础解卦',
    ai_interpretation TEXT COMMENT 'AI智能解读',
    used_ai BOOLEAN NOT NULL DEFAULT FALSE COMMENT '是否使用AI',
    divination_time DATETIME NOT NULL COMMENT '占卜时间',
    created_at DATETIME NOT NULL COMMENT '创建时间',
    ip_address VARCHAR(50) COMMENT 'IP地址',
    user_agent VARCHAR(500) COMMENT '用户代理',
    remark TEXT COMMENT '备注',
    is_favorite BOOLEAN NOT NULL DEFAULT FALSE COMMENT '是否收藏',
    tags VARCHAR(200) COMMENT '标签JSON',
    INDEX idx_user_id (user_id),
    INDEX idx_openid (openid),
    INDEX idx_created_at (created_at),
    INDEX idx_original_hexagram (original_hexagram_id),
    FOREIGN KEY (user_id) REFERENCES mini_program_user(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='占卜记录表';
